name: CI/CD - Build & Deploy to EC2 (Docker Hub)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            set -euo pipefail

            APP_NAME="re-shopping-cart-web-app"
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:latest"
            APP_DIR="/opt/${APP_NAME}"
            ENV_FILE="${APP_DIR}/.env.prod"

            mkdir -p "${APP_DIR}"

            if [ ! -f "${ENV_FILE}" ]; then
              echo "Missing ${ENV_FILE} on EC2. Create it (copy from .env.prod) before deploying."
              exit 1
            fi

            docker pull "${IMAGE}"

            if docker ps -a --format '{{.Names}}' | grep -q "^${APP_NAME}$"; then
              docker stop "${APP_NAME}" || true
              docker rm "${APP_NAME}" || true
            fi

            docker run -d \
              --name "${APP_NAME}" \
              --restart unless-stopped \
              --env-file "${ENV_FILE}" \
              -e "SPRING_PROFILES_ACTIVE=prod" \
              -p 80:8080 \
              "${IMAGE}"

            docker image prune -f || true
